// lib/profilesets.js
// Turns a user-pasted SimC addon export plus some sim parameters into a
// concrete .simc file. Handles three modes: quick sim, droptimizer (one
// profileset per candidate drop), and top gear (one profileset per bag item).

const GEAR_SLOTS = [
  'head', 'neck', 'shoulder', 'back', 'chest', 'wrist', 'hands', 'waist',
  'legs', 'feet', 'finger1', 'finger2', 'trinket1', 'trinket2',
  'main_hand', 'off_hand',
];

// Slots that exist in pairs. When we want to test a candidate ring/trinket we
// have to consider replacing either occupant, so each candidate spawns two
// profilesets (one per occupied slot).
const PAIRED_SLOTS = {
  finger:  ['finger1', 'finger2'],
  trinket: ['trinket1', 'trinket2'],
};

/**
 * Quote a profileset name for the SimC parser. Profileset names are wrapped
 * in double-quotes; embedded quotes get escaped.
 */
function q(name) {
  return `"${String(name).replace(/"/g, '\\"')}"`;
}

/**
 * Pull the slot keyword off the front of a SimC gear line.
 * "finger1=,id=123,bonus_id=4/5"  ->  "finger1"
 * Returns null if the line doesn't look like a gear line.
 */
function detectSlot(line) {
  const m = line.match(/^\s*([a-z_][a-z_0-9]*)\s*=/i);
  if (!m) return null;
  const slot = m[1].toLowerCase();
  return GEAR_SLOTS.includes(slot) ? slot : null;
}

/**
 * Strip the slot prefix from a gear line, leaving just the item descriptor.
 * "finger1=,id=123,bonus_id=4"  ->  ",id=123,bonus_id=4"
 */
function stripSlotPrefix(line) {
  return line.replace(/^\s*[a-z_][a-z_0-9]*\s*=/i, '');
}

/**
 * Try to extract a friendly label for a gear line. The SimC addon writes a
 * trailing comment like "# Voidlight Bindings (610)" on each gear line; if
 * that's present we use it. Otherwise we fall back to "id=NNNN".
 */
function gearLabel(line) {
  const cm = line.match(/#\s*(.+?)\s*$/);
  if (cm) return cm[1];
  const idm = line.match(/[?,]id=(\d+)/);
  if (idm) return `id=${idm[1]}`;
  return line.trim().slice(0, 40);
}

/**
 * Mode 1: Quick Sim — just pass the profile straight through.
 */
export function buildQuickSim(profile) {
  // Defensive trim only; SimC is happy with the addon's output as-is.
  return profile.trim() + '\n';
}

/**
 * Mode 2: Droptimizer — given a base profile and a list of candidate items
 * (one per line, in SimC gear-line format like "finger1=,id=...,bonus_id=..."),
 * produce a .simc file whose profilesets each swap one candidate into its slot.
 *
 * For finger/trinket candidates we emit two profilesets (one swapping finger1,
 * one swapping finger2) so the user can see which existing piece to replace.
 *
 * @param {string} baseProfile
 * @param {string[]} candidateLines
 * @returns {string}
 */
export function buildDroptimizer(baseProfile, candidateLines) {
  const sets = [];
  let counter = 0;

  for (const rawLine of candidateLines) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;

    const slot = detectSlot(line);
    if (!slot) {
      // Skip silently rather than fail the whole job; the UI will report
      // skipped lines from a separate validate-step before submission.
      continue;
    }

    const label = gearLabel(line);
    const itemPart = stripSlotPrefix(line);

    // Determine which slot variants to test. For a generic "finger" candidate
    // we want both finger1 and finger2 swaps; same for trinkets.
    let targetSlots;
    if (slot === 'finger1' || slot === 'finger2') {
      targetSlots = PAIRED_SLOTS.finger;
    } else if (slot === 'trinket1' || slot === 'trinket2') {
      targetSlots = PAIRED_SLOTS.trinket;
    } else {
      targetSlots = [slot];
    }

    for (const targetSlot of targetSlots) {
      counter++;
      const psName = targetSlots.length > 1
        ? `${label} [${targetSlot}]`
        : `${label}`;
      sets.push(`profileset.${q(psName)}+=${targetSlot}=${itemPart}`);
    }
  }

  // We append a header comment so anyone opening input.simc later can tell
  // what the run was for at a glance.
  const header = [
    '# Generated by simlocal (droptimizer mode)',
    `# ${counter} profileset(s) across ${candidateLines.length} candidate line(s)`,
    '',
  ].join('\n');

  // Important: profileset directives must appear AFTER the base profile.
  return header + baseProfile.trim() + '\n\n' + sets.join('\n') + '\n';
}

/**
 * Mode 3: Top Gear — parse the SimC addon's bag dump (lines that begin with
 * "#" and are followed by a gear-line) and build one profileset per swap.
 *
 * The addon writes bag items like:
 *
 *   ### Gear from Bags
 *   #trinket1=,id=23456,bonus_id=...   # Some Trinket Name (610)
 *   #finger1=,id=34567,bonus_id=...    # Some Ring (615)
 *
 * For each bag item we generate profileset(s) the same way as droptimizer
 * (paired slots get two variants). The base profile we feed to SimC has the
 * bag-item comment lines stripped — they're only there for our parser.
 *
 * @param {string} baseProfile  The full addon export, including bag comments.
 * @returns {{simc:string, count:number, skipped:number}}
 */
export function buildTopGear(baseProfile) {
  const lines = baseProfile.split(/\r?\n/);
  const candidates = [];
  const cleanProfileLines = [];

  // We accept both "#slot=..." (commented gear) and a separator-style format
  // where bag items sit under a "### Gear from Bags" header. The addon uses
  // both depending on version; treating any "#<slot>=" line as a candidate
  // covers both.
  for (const line of lines) {
    const m = line.match(/^#\s*([a-z_][a-z_0-9]*)\s*=(.*)$/i);
    if (m && GEAR_SLOTS.includes(m[1].toLowerCase())) {
      // Reconstruct the gear line without the leading "#".
      candidates.push(`${m[1]}=${m[2]}`);
      // Drop these from the base profile so SimC doesn't see them as actual
      // equipped items (they're just bag inventory).
      continue;
    }
    cleanProfileLines.push(line);
  }

  const cleanProfile = cleanProfileLines.join('\n').trim();
  let skipped = 0;
  const sets = [];

  for (const cand of candidates) {
    const slot = detectSlot(cand);
    if (!slot) { skipped++; continue; }

    const label = gearLabel(cand);
    const itemPart = stripSlotPrefix(cand);

    let targetSlots;
    if (slot === 'finger1' || slot === 'finger2')   targetSlots = PAIRED_SLOTS.finger;
    else if (slot === 'trinket1' || slot === 'trinket2') targetSlots = PAIRED_SLOTS.trinket;
    else targetSlots = [slot];

    for (const ts of targetSlots) {
      const psName = targetSlots.length > 1 ? `${label} [${ts}]` : label;
      sets.push(`profileset.${q(psName)}+=${ts}=${itemPart}`);
    }
  }

  const header = [
    '# Generated by simlocal (top gear mode)',
    `# ${sets.length} profileset(s) from ${candidates.length} bag item(s)` +
      (skipped ? `, ${skipped} skipped` : ''),
    '',
  ].join('\n');

  return {
    simc: header + cleanProfile + '\n\n' + sets.join('\n') + '\n',
    count: sets.length,
    skipped,
  };
}
