// lib/profilesets.js
// Turns a user-pasted SimC addon export plus some sim parameters into a
// concrete .simc file. Handles three modes: quick sim, droptimizer (one
// profileset per candidate drop), and top gear (one profileset per bag item).

import { filterBagItems } from './itemfilter.js';

const GEAR_SLOTS = [
  'head', 'neck', 'shoulder', 'back', 'chest', 'wrist', 'hands', 'waist',
  'legs', 'feet', 'finger1', 'finger2', 'trinket1', 'trinket2',
  'main_hand', 'off_hand',
];

// Slots that exist in pairs. When we want to test a candidate ring/trinket we
// have to consider replacing either occupant, so each candidate spawns two
// profilesets (one per occupied slot).
const PAIRED_SLOTS = {
  finger:  ['finger1', 'finger2'],
  trinket: ['trinket1', 'trinket2'],
};

/**
 * Quote a profileset name for the SimC parser. Profileset names are wrapped
 * in double-quotes; embedded quotes get escaped.
 */
function q(name) {
  return `"${String(name).replace(/"/g, '\\"')}"`;
}

/**
 * Pull the slot keyword off the front of a SimC gear line.
 * "finger1=,id=123,bonus_id=4/5"  ->  "finger1"
 * Returns null if the line doesn't look like a gear line.
 */
function detectSlot(line) {
  const m = line.match(/^\s*([a-z_][a-z_0-9]*)\s*=/i);
  if (!m) return null;
  const slot = m[1].toLowerCase();
  return GEAR_SLOTS.includes(slot) ? slot : null;
}

/**
 * Strip the slot prefix from a gear line, leaving just the item descriptor.
 * "finger1=,id=123,bonus_id=4"  ->  ",id=123,bonus_id=4"
 */
function stripSlotPrefix(line) {
  return line.replace(/^\s*[a-z_][a-z_0-9]*\s*=/i, '');
}

/**
 * Pull the numeric item id out of a gear line.
 * ",id=219308,bonus_id=4824"  ->  "219308"
 */
function extractItemId(line) {
  const m = line.match(/[?,\s]id=(\d+)/);
  return m ? m[1] : null;
}

/**
 * Sanitize a label so it can safely live inside a SimC profileset name.
 *
 * Critical: SimC uses '=' as its assignment operator, so a profileset name
 * containing '=' (e.g. "id=249913") confuses the parser. It either fails to
 * register the profileset entirely or merges everything under a name that's
 * been split at the '='. We strip anything that could cause trouble and cap
 * the length so SimC's name-handling code has an easier time.
 */
function sanitizeLabel(s) {
  return String(s ?? '')
    .replace(/=/g, ' ')
    .replace(/["\\]/g, '')
    .replace(/\s+/g, ' ')
    .trim()
    .slice(0, 80) || 'item';
}

/**
 * Try to extract a friendly label from a SimC gear line. Used by Droptimizer
 * mode where users paste candidate lines with optional trailing comments
 * like "id=900001,bonus_id=... # My Cool Trinket".
 *
 * For Top Gear mode this isn't used — see buildTopGear, which carries the
 * label from the previous line because that's how the addon emits them.
 */
function gearLabelFromTrailingComment(line) {
  const cm = line.match(/#\s*(.+?)\s*$/);
  if (cm) return cm[1];
  const id = extractItemId(line);
  if (id) return `Item ${id}`;
  return line.trim().slice(0, 40);
}

// ---------------------------------------------------------------------------
// Mode 1: Quick Sim — pass the profile straight through.
// ---------------------------------------------------------------------------

export function buildQuickSim(profile) {
  return profile.trim() + '\n';
}

// ---------------------------------------------------------------------------
// Mode 2: Droptimizer — one profileset per user-provided candidate line.
// ---------------------------------------------------------------------------

/**
 * @param {string} baseProfile
 * @param {string[]} candidateLines
 * @returns {string}
 */
export function buildDroptimizer(baseProfile, candidateLines) {
  const sets = [];
  const usedNames = new Set();
  let counter = 0;

  for (const rawLine of candidateLines) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;

    const slot = detectSlot(line);
    if (!slot) continue;

    const label = sanitizeLabel(gearLabelFromTrailingComment(line));
    // Drop the trailing comment from the SimC payload itself; we've already
    // captured it as the label.
    const itemPart = stripSlotPrefix(line).replace(/\s*#.*$/, '');

    let targetSlots;
    if (slot === 'finger1' || slot === 'finger2') {
      targetSlots = PAIRED_SLOTS.finger;
    } else if (slot === 'trinket1' || slot === 'trinket2') {
      targetSlots = PAIRED_SLOTS.trinket;
    } else {
      targetSlots = [slot];
    }

    for (const ts of targetSlots) {
      const baseName = targetSlots.length > 1 ? `${label} [${ts}]` : label;
      const unique = ensureUniqueName(usedNames, baseName);
      counter++;
      sets.push(`profileset.${q(unique)}+=${ts}=${itemPart}`);
    }
  }

  const header = [
    '# Generated by LocalSimcraft (droptimizer mode)',
    `# ${counter} profileset(s) across ${candidateLines.length} candidate line(s)`,
    '',
  ].join('\n');

  return header + baseProfile.trim() + '\n\n' + sets.join('\n') + '\n';
}

// ---------------------------------------------------------------------------
// Mode 3: Top Gear — extract bag items from the addon export.
// ---------------------------------------------------------------------------

/**
 * The in-game SimC addon's "Show Bag Items" output looks like:
 *
 *   ### Gear from Bags
 *   #
 *   # Mask of Darkest Intent (269)        <- friendly label, line N
 *   #
 *   #head=,id=249913,bonus_id=6652/...    <- gear line, line N+2
 *   #
 *   # Spellsnap Shadowmask (266)
 *   #
 *   #head=,id=251109,bonus_id=...
 *   ...
 *
 * The label sits two lines above the gear line, with an empty "#" between.
 * Our parser carries the most recent meaningful comment forward as the
 * pending label until either:
 *   - a bag-item gear line consumes it (label becomes that profileset's name)
 *   - a non-comment, non-empty line resets it (we've left the bag section)
 *
 * Empty "#" lines and "### Section Headers" preserve the pending label —
 * they're separators, not new labels.
 *
 * @param {string} baseProfile  The full addon export, including bag comments.
 * @returns {{simc:string, count:number, skipped:number}}
 */
export function buildTopGear(baseProfile) {
  const lines = baseProfile.split(/\r?\n/);
  const candidates = [];   // [{ slotLine, label }]
  const cleanProfileLines = [];
  let pendingLabel = null;

  for (const line of lines) {
    // 1) Bag-item gear line: "#slot=,id=...,bonus_id=..."
    const slotM = line.match(/^#\s*([a-z_][a-z_0-9]*)\s*=(.*)$/i);
    if (slotM && GEAR_SLOTS.includes(slotM[1].toLowerCase())) {
      candidates.push({
        slotLine: `${slotM[1]}=${slotM[2]}`,
        label:    pendingLabel,
      });
      pendingLabel = null;
      // Don't push to cleanProfileLines — we don't want the bag gear line
      // sitting in the profile, only the profileset directives we're about
      // to emit.
      continue;
    }

    // 2) "### section header" — preserve pendingLabel; pass through.
    if (/^\s*###/.test(line)) {
      cleanProfileLines.push(line);
      continue;
    }

    // 3) Single-hash content comment: "# Item Name (ilvl)" — set as label.
    //    Pattern: "#" then at least one whitespace then non-empty content.
    //    This rules out empty "#" separators (handled in branch 4).
    const labelM = line.match(/^#\s+(\S.*?)\s*$/);
    if (labelM) {
      pendingLabel = labelM[1];
      cleanProfileLines.push(line);
      continue;
    }

    // 4) Empty "#" separator — preserve pendingLabel; pass through.
    if (/^\s*#\s*$/.test(line)) {
      cleanProfileLines.push(line);
      continue;
    }

    // 5) Anything else: a real (non-comment) profile line. The bag section is
    //    over for now — drop the pending label so we don't accidentally label
    //    a future bag item with a stale name.
    pendingLabel = null;
    cleanProfileLines.push(line);
  }

  const cleanProfile = cleanProfileLines.join('\n').trim();

  // Run candidates through the heuristic filter: drops caster items for
  // melee specs, defers off-hands when 2H is equipped, generates combo
  // (1H+OH) profilesets when the player is on a 2H but has bag pieces that
  // would let them dual-wield, etc. See lib/itemfilter.js.
  const filtered = filterBagItems(cleanProfile, candidates, detectSlot);

  const sets = [];
  const usedNames = new Set();
  let invalidSlot = 0;

  // 1) Single-slot swaps for everything the filter accepted.
  for (const cand of filtered.accepted) {
    const slot = detectSlot(cand.slotLine);
    if (!slot) { invalidSlot++; continue; }
    const itemPart = stripSlotPrefix(cand.slotLine);

    const rawLabel = cand.label || `Item ${extractItemId(cand.slotLine) || 'unknown'}`;
    const safeLabel = sanitizeLabel(rawLabel);

    let targetSlots;
    if (slot === 'finger1' || slot === 'finger2') {
      targetSlots = PAIRED_SLOTS.finger;
    } else if (slot === 'trinket1' || slot === 'trinket2') {
      targetSlots = PAIRED_SLOTS.trinket;
    } else {
      targetSlots = [slot];
    }

    for (const ts of targetSlots) {
      const baseName = targetSlots.length > 1 ? `${safeLabel} [${ts}]` : safeLabel;
      const unique = ensureUniqueName(usedNames, baseName);
      sets.push(`profileset.${q(unique)}+=${ts}=${itemPart}`);

      // If this is a 2H bag item replacing the player's dual-wield setup,
      // also clear the off-hand for this profileset so SimC doesn't try
      // to keep the old OH equipped alongside a 2H (which would be illegal
      // and produce nonsense numbers).
      if (cand.extras?.off_hand === 'CLEAR') {
        sets.push(`profileset.${q(unique)}+=off_hand=`);
      }
    }
  }

  // 2) Combinatorial 1H + OH profilesets, for the case where the player has
  //    a 2H equipped and bag pieces that would let them dual-wield. SimC
  //    accepts multiple `profileset.NAME+=` lines that all apply to the same
  //    named profileset, so we emit two lines (main_hand swap and off_hand
  //    swap) per combo.
  for (const combo of filtered.combos) {
    const safeLabel = sanitizeLabel(combo.label);
    const unique = ensureUniqueName(usedNames, safeLabel);
    const mhPart = stripSlotPrefix(combo.mhCand.slotLine);
    const ohPart = stripSlotPrefix(combo.ohCand.slotLine);
    sets.push(`profileset.${q(unique)}+=main_hand=${mhPart}`);
    sets.push(`profileset.${q(unique)}+=off_hand=${ohPart}`);
  }

  // Header includes a summary so the input.simc artifact tells you what
  // was filtered without having to dig through job logs.
  const headerLines = [
    '# Generated by LocalSimcraft (top gear mode)',
    `# Detected primary stat: ${filtered.primaryStat || 'unknown'}`,
    `# Equipped weapon config: ${filtered.weaponConfig.kind}` +
      (filtered.weaponConfig.mainName ? ` (${filtered.weaponConfig.mainName})` : ''),
    `# ${filtered.accepted.length} accepted, ${filtered.skipped.length} skipped, ${filtered.combos.length} combo(s) — total ${sets.length} profileset directive(s)`,
  ];
  if (filtered.skipped.length > 0) {
    headerLines.push('# Skipped items:');
    for (const s of filtered.skipped) {
      headerLines.push(`#   - [${s.slot}] ${s.label || '(unnamed)'} — ${s.reason}`);
    }
  }
  headerLines.push('');
  const header = headerLines.join('\n');

  return {
    simc: header + cleanProfile + '\n\n' + sets.join('\n') + '\n',
    count: sets.length,
    skipped: filtered.skipped,    // now an array of {label, slot, reason}
    accepted: filtered.accepted.length + filtered.combos.length,
    primaryStat: filtered.primaryStat,
    weaponConfig: filtered.weaponConfig,
  };
}

/**
 * Two bag items can share the same display name (e.g. multiple "Cloak of the
 * Fallen Cardinal (266)" rolls with different bonus_ids). Profileset names
 * must be unique or SimC silently merges them and you lose data points; we
 * append " #2", " #3", etc. as needed.
 */
function ensureUniqueName(used, name) {
  if (!used.has(name)) { used.add(name); return name; }
  let n = 2;
  while (used.has(`${name} #${n}`)) n++;
  const next = `${name} #${n}`;
  used.add(next);
  return next;
}
